name: Sync main to noconf

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so branches can be worked with

      - name: Set up Git user for the action
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch branches
        run: |
          git fetch origin

      - name: Checkout noconf branch
        run: |
          git checkout noconf

      - name: Reset noconf to match main
        run: |
          git reset --hard origin/main  # Reset noconf to match main's state

      - name: Remove the .obsidian directory from noconf
        run: |
          rm -rf .obsidian  # Remove the .obsidian directory

      - name: Commit the deletion of .obsidian
        run: |
          git add .
          git commit -m "Sync noconf with main" || echo "No changes to commit"

      - name: Push the updated noconf branch
        run: |
          git push --force origin noconf
