name: Sync main to noconf

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user for the action
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch and switch to noconf
        run: |
          # Fetch the latest changes from both main and noconf
          git fetch origin

          # Checkout the main branch
          git checkout main
          git pull origin main

          # Switch to noconf branch
          git checkout noconf
          git pull origin noconf

      - name: Merge main into noconf with "ours" strategy to resolve conflicts
        run: |
          # Merge main into noconf, keeping the changes in noconf for conflicts
          git merge -X ours main || true # The "|| true" ensures the step doesn't fail even if there's a merge conflict

      - name: Push the updated noconf branch
        run: |
          git push origin noconf
